### ISSUE TITLE
processing error?

### ISSUE THREAD

**Issue by CrazyFangirlCat** [greysdawn/pluralkit-web#68]
Previously would not let me save the information or add information I wanted to add to the bots. Now it won't even let me log-in or process that I'm pressing the "submit" button when I input my pk token, And when it does try to process it, it only ever says "Something went wrong. Please try again".

**Comment by greysdawn** [comment]
Unfortunately, there's been some issues with the site lately and we're not really sure where all of them are coming from. Some issues are because of PK's API itself having issues, others seem to be entirely unrelated. We're taking a look right now but for the moment it's probably best to use [pk-webs](https://pk-webs-beta.spectralitree.com) instead of our website

**Comment by greysdawn** [comment]
Closing for now, will be pinning this too

If you're having issues with logging in or saving data, try joining [PK's support server](https://discord.gg/PczBt78) first and seeing if there are any API issues going on. If there aren't any, you can join [our server](https://discord.gg/EvDmXGt) and bring it up there, or comment on this issue and we can try taking a look
